name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install npm dependencies for Deno
        run: deno cache --node-modules-dir

      - name: Publish package
        run: npx jsr publish
